import type { NextPage } from "next";
import Head from "next/head";
import ReactPlayer from "react-player";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <video width="320" height="240" controls>
        <source
          src="https://api-v2.salesfra.me/stream/69690b8a498ce98dab84a894691952e2/2/mi4n275/sf_6345653b2350d/663efb07c40f4c4dc8de9804852b59fc"
          type="video/mp4"
        />
        Your browser does not support the video tag.
      </video>
    </main>
  </div>
);

export default Home;
