import type { NextPage } from "next";
import Head from "next/head";
import ReactPlayer from "react-player";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <video width="320" height="240" controls>
        <source
          src="https://api-v2.salesfra.me/stream/c5d4aab9298ead431380049c923a6171/31/m9w2Lpv/sf_6345679759911/67535f5028abd33b7a01ea75f0f2f472"
          type="video/mp4"
        />
        Your browser does not support the video tag.
      </video>
    </main>
  </div>
);

export default Home;
